# Generated by Django 3.1.3 on 2021-01-28 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='client',
            name='dni',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Dni'),
        ),
    ]
